# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.0.1

methodology: network_validation   # technique used in the validation:
                                  # - network_validation: to validate a single network file specified in "network_validation" block

datasets:
  demand: ["ourworldindata"]  # list of datasets sources to use. A subset of 'ourworldindata'
  installed_capacity: ["irena"]  # list of datasets sources to use. A subset of 'irena'
  electricity_generation: ["irena"] # list of datasets sources to use. A subset of 'irena'
  # energy_dispatch: []  # list of datasets sources to validate energy dispatch. Not yet supported
  # network: []  # list of datasets sources to validate networks. Not yet supported

network_validation:
  name: "validation_name" # Unique identifier for the validation run. Change it to keep outputs from different validation configurations separate.
  network_path: "resources/example_DE.nc" # File to the PyPSA network file to validate
  year: [2021]  # year of the network to validate
  countries: ['DE', 'FR']  # country of the network to validate
  shapefile: false
  validate_cross_border_capacity: true # validation of cross border capacity

plot_osm_grid_network:
  grid_path: "tests/fixtures"
  line_voltages: [132., 220., 300., 380., 500., 750.]
  voltage_colors: ["#deb887", "#ff7f50", "#cd5c5c", "#9400D3", "#00ced1", "#ffffff"]  # colors for each voltage level in line_voltages
  plot_circuits: false  # whether to plot the number of circuits on the lines if available
