# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-earth-status
channels:
- conda-forge
- bioconda
dependencies:
- python >=3.10,<3.13
- cartopy
- country_converter
- geopandas
- graphviz
- matplotlib
- numpy
- pandas
- pulp <2.8
- pyproj
- pypsa >=0.25,<=0.30
- pyyaml
- shapely
- snakemake-minimal
