name: Test workflows

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * TUE"

# Cancel any in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: OS
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v5

    - name: Use env file
      run: |
        echo "Using repository environment file."
        echo "env_file=envs/environment.yaml" >> $GITHUB_ENV

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: pypsa-earth-status
        channel-priority: strict
        conda-remove-defaults: true

    - name: Cache Conda env
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}', env.env_file)) }}
      id: cache-env

    - name: Update environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      run: conda env update -n pypsa-earth-status -f ${{ env.env_file }}

    - name: Conda list
      run: conda list

    - name: Setup GTD transmission data
      run: |
        mkdir -p data/electricity_transmission
        ls -la data/electricity_transmission/

    - name: Run Test
      run: snakemake -j 1 visualize_data --forceall
